language: node_js
services:
  - docker

before_install:
  - docker build -t stephenchinkenvun/youtube-stats -f Dockerfile.dev .

script:
  - docker run stephenchinkenvun/youtube-stats npm run test -- --coverage


  #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